### ISSUE TITLE
there should be spaces between commas in the same field

### ISSUE THREAD

**Issue by andersgs** [MDU-PHL/LisSero#1]
Hi Jason.

When printing multiple elements that are in a field separated by commas, there should be no space between the comma and the record. That makes parsing the output a bit of a nightmare.

So:

    1/2b, 3b, 7

Should be:

    1/2b,3b,7

So, the whole line looks like this:

    contigs.fa   1/2b,3b,7     ORF2819,Prs

Anders.

**Comment by kwongj** [comment]
Fixed.

**Comment by tseemann** [comment]
@kwongj just a little tip - if you put the phrase "Issue #1" in the github commit message, it will automatically link the commit to this thread!

**Comment by kwongj** [comment]
Closed #1
