### ISSUE TITLE
issues downloading the dependency EMBOSS PrimerSearch

### ISSUE THREAD

**Issue by borgesvitor** [MDU-PHL/LisSero#2]
Dear Jason,

First of all, congratulations for LisSero. It will be a very useful tool!!!

I am trying to install it on a Unix environment, but the link provided in the HELP file regarding the download of EMBOSS PrimerSearch is not working...(and consequently, the LIsSero doesn't run!)

I would like to kindly ask you if you could provide us the correct link, or another alternative to install PrimerSearch. 

I am looking forward to testting LisSero!!!

Best regards,

Vítor Borges

**Comment by andersgs** [comment]
It seems that link is dead, and the EMBOSS package has gone missing at least 8 months ago:

https://www.biostars.org/p/147960/

There are two options. Download a 6.5.7 version from the old folder:
ftp://emboss.open-bio.org/pub/EMBOSS/old/6.5.0/

Or, download the 6.6.0 version from this link provided in the biostars page above. 

http://debian.rub.de/ubuntu/pool/universe/e/emboss/emboss_6.6.0.orig.tar.gz

We will need to update the README to point to the right direction. 

Thank you, Vitor.
