### ISSUE TITLE
Clarify and detect min blast version

### ISSUE THREAD

**Issue by tseemann** [MDU-PHL/LisSero#25]
Fails on blast 2.5
please make lissero check `blast -version` before running.
And add to docs

**Comment by andersgs** [comment]
In what context were we using blast 2.5? Just curious. We test against 2.9, 2.10, and 2.11. 

Is it a database version issue? Blast DB V4 vs V5?

**Comment by abcdtree** [comment]
@andersgs conda problem. I tested that when you run `conda install -c bioconda blast` It will install 2.5.0 for you. I think changed the readme file and try to add warning in the script

**Comment by andersgs** [comment]
Never mind. I see the other issue now.
